FROM node:20-alpine AS builder
WORKDIR /app
RUN npm install -g pnpm@11.22.0

COPY . .
RUN pnpm install --frozen-lockfile=false
RUN pnpm --filter @mailtrace/shared build
RUN pnpm --filter @mailtrace/web build

FROM nginx:alpine AS runner
COPY --from=builder /app/apps/web/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
